package com.hpe.sylar.puzzlers.b;
    /**
     * Generated by the IBM IDL-to-Java compiler, version 1.0
     * from F:\TestRoot\apps\a1\units\include\PolicyHome.idl
     * Wednesday, June 17, 1998 6:44:40 o’clock AM GMT+00:00
     */
    public class puzzle_15{
        public static void main(String[] args){
            //输出是什么？
            System.out.print("Hello world");

            //intellij idea忽略部分类编译错误
            //https://my.oschina.net/magicly007/blog/158407

//            问题在于注释的第三行，它包含了字符\units。这些字符以反斜杠（\）以及紧
//            跟着的字母u 开头的，而它（\u）表示的是一个Unicode 转义字符的开始。遗憾
//            的是，这些字符后面没有紧跟四个十六进制的数字，因此，这个Unicode 转义字
//            符是病构的，而编译器则被要求拒绝该程序
        }
    }
